import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { internalLocations, services } from "../../site-data";

type Props = { params: Promise<{ slug: string }> };
export function generateStaticParams() { return services.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { slug } = await params; const service = services.find((item) => item.slug === slug); return service ? { title: service.title, description: `${service.intro} Check Safawala Rishikesh availability for your wedding date.`, alternates: { canonical: `https://safawalarishikesh.com/services/${slug}` } } : {}; }

export default async function ServicePage({ params }: Props) {
  const { slug } = await params; const service = services.find((item) => item.slug === slug); if (!service) notFound();
  const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: service.faqs.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) };
  return <><header className="site-header"><a className="brand" href="/"><span className="brand-mark">S</span><span><strong>SAFAWALA</strong><small>RISHIKESH</small></span></a><nav><a href="/#services">Services</a><a href="/#gallery">Gallery</a><a href="/#areas">Areas</a><a href="/#faq">FAQs</a></nav><a className="header-cta" href="https://wa.me/919725295691">Check availability</a></header><main className="subpage-main"><section className="subpage-hero section-shell"><div><div className="breadcrumbs"><a href="/">Home</a> / <a href="/#services">Services</a> / {service.name}</div><p className="eyebrow">Professional wedding styling</p><h1>{service.title}</h1><p>{service.intro}</p><a className="button primary" href={`https://wa.me/919725295691?text=${encodeURIComponent(`Hello, I want details about ${service.name} in Rishikesh.`)}`}>Check this service</a></div><aside className="subpage-note"><strong>Focused search intent</strong><br />Related phrases are consolidated here so couples get one complete answer instead of thin pages for every keyword variation.</aside></section><section className="subpage-content section-shell"><article><p className="eyebrow">How the service works</p><h2>Designed around the wedding, not a template.</h2><p>{service.detail}</p><p>Before confirmation, we review the Rishikesh venue, guest quantity, ceremony timing and outfit references. That creates enough room for the groom's styling and a clear tying sequence for relatives or baraatis.</p><div className="related-links">{internalLocations.slice(0,8).map((location) => <a href={`/areas/${location.slug}`} key={location.slug}>{location.name}</a>)}</div></article><aside className="subpage-card"><h3>Included in the planning</h3><ul><li>Style and colour discussion</li><li>Groom-ready timing</li><li>Team size recommendation</li><li>Venue arrival coordination</li><li>WhatsApp confirmation</li></ul><a className="button dark" href="/#quote">Request a quote</a></aside></section><section className="subpage-faq section-shell"><p className="eyebrow">Service FAQs</p><h2>Helpful answers for {service.name.toLowerCase()}.</h2><div className="faq-list">{service.faqs.map(([question, answer], index) => <details key={question} open={index === 0}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></section></main><footer><div className="copyright section-shell"><span>© 2026 Safawala Rishikesh</span><a href="/">Return to the Rishikesh website</a></div></footer><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} /></>;
}
